IF OBJECT_ID('R3_STOP', 'U') IS NOT NULL
DROP TABLE R3_STOP;

IF OBJECT_ID('R2_OUTBOUND_SHIPMENTS', 'U') IS NOT NULL
DROP TABLE R2_OUTBOUND_SHIPMENTS;

IF OBJECT_ID('R2_STOP', 'U') IS NOT NULL
DROP TABLE R2_STOP;

IF OBJECT_ID('R1_OUTBOUND_SHIPMENTS', 'U') IS NOT NULL
DROP TABLE R1_OUTBOUND_SHIPMENTS;

IF OBJECT_ID('DELIVERY_ROUTE', 'U') IS NOT NULL
DROP TABLE DELIVERY_ROUTE;

IF OBJECT_ID('INVENTORY', 'U') IS NOT NULL
DROP TABLE INVENTORY;

IF OBJECT_ID('IS_LINE_ITEMS', 'U') IS NOT NULL
DROP TABLE IS_LINE_ITEMS;

IF OBJECT_ID('VEHICLE', 'U') IS NOT NULL
DROP TABLE VEHICLE;

IF OBJECT_ID('STORAGE_LOCATION', 'U') IS NOT NULL
DROP TABLE STORAGE_LOCATION;

IF OBJECT_ID('PO_LINE_ITEMS', 'U') IS NOT NULL
DROP TABLE PO_LINE_ITEMS;

IF OBJECT_ID('SUPPLIERS_GENERATES_PURCHASE_ORDERS', 'U') IS NOT NULL
DROP TABLE SUPPLIERS_GENERATES_PURCHASE_ORDERS;

IF OBJECT_ID('CLIENT_CONSOLIDATES_PURCHASE_ORDER', 'U') IS NOT NULL
DROP TABLE CLIENT_CONSOLIDATES_PURCHASE_ORDER;

IF OBJECT_ID('INBOUND_SHIPMENTS', 'U') IS NOT NULL
DROP TABLE INBOUND_SHIPMENTS;

IF OBJECT_ID('WAREHOUSE_PERSONNEL', 'U') IS NOT NULL
DROP TABLE WAREHOUSE_PERSONNEL;

IF OBJECT_ID('DRIVER', 'U') IS NOT NULL
DROP TABLE DRIVER;

IF OBJECT_ID('EMPLOYEE_HAS_CERTIFICATIONS', 'U') IS NOT NULL
DROP TABLE EMPLOYEE_HAS_CERTIFICATIONS;

IF OBJECT_ID('PRODUCT_HAS_HANDLING_REQUIREMENTS', 'U') IS NOT NULL
DROP TABLE PRODUCT_HAS_HANDLING_REQUIREMENTS;

IF OBJECT_ID('CO_LINE_ITEMS', 'U') IS NOT NULL
DROP TABLE CO_LINE_ITEMS;

IF OBJECT_ID('STORAGE_ZONE', 'U') IS NOT NULL
DROP TABLE STORAGE_ZONE;

IF OBJECT_ID('WAREHOUSE_HAS_TEMPERATURE_CONTROL_CAPABILITIES', 'U') IS NOT NULL
DROP TABLE WAREHOUSE_HAS_TEMPERATURE_CONTROL_CAPABILITIES;

IF OBJECT_ID('WAREHOUSE_PICKUP_STOP', 'U') IS NOT NULL
DROP TABLE WAREHOUSE_PICKUP_STOP;

IF OBJECT_ID('PURCHASE_ORDER', 'U') IS NOT NULL
DROP TABLE PURCHASE_ORDER;

IF OBJECT_ID('CLIENT_WAREHOUSE_STORAGE_CONTRACT', 'U') IS NOT NULL
DROP TABLE CLIENT_WAREHOUSE_STORAGE_CONTRACT;

IF OBJECT_ID('EMPLOYEE', 'U') IS NOT NULL
DROP TABLE EMPLOYEE;

IF OBJECT_ID('CUSTOMER_ORDER', 'U') IS NOT NULL
DROP TABLE CUSTOMER_ORDER;

IF OBJECT_ID('SUPPLIERS', 'U') IS NOT NULL
DROP TABLE SUPPLIERS;

IF OBJECT_ID('PRODUCT', 'U') IS NOT NULL
DROP TABLE PRODUCT;

IF OBJECT_ID('SUPPLY', 'U') IS NOT NULL
DROP TABLE SUPPLY;

IF OBJECT_ID('HANDLING_REQUIREMENTS', 'U') IS NOT NULL
DROP TABLE HANDLING_REQUIREMENTS;

IF OBJECT_ID('WAREHOUSE', 'U') IS NOT NULL
DROP TABLE WAREHOUSE;

IF OBJECT_ID('TEMPERATURE_CONTROL_CAPABILITIES', 'U') IS NOT NULL
DROP TABLE TEMPERATURE_CONTROL_CAPABILITIES;

IF OBJECT_ID('ROUTE_STATUS_CODES', 'U') IS NOT NULL
DROP TABLE ROUTE_STATUS_CODES;

IF OBJECT_ID('R1_STOP', 'U') IS NOT NULL
DROP TABLE R1_STOP;

IF OBJECT_ID('SHIPMENT_STATUS', 'U') IS NOT NULL
DROP TABLE SHIPMENT_STATUS;

IF OBJECT_ID('PO_STATUS', 'U') IS NOT NULL
DROP TABLE PO_STATUS;

IF OBJECT_ID('ORDER_STATUS_CODE', 'U') IS NOT NULL
DROP TABLE ORDER_STATUS_CODE;

IF OBJECT_ID('CUSTOMER', 'U') IS NOT NULL
DROP TABLE CUSTOMER;

IF OBJECT_ID('COUNTRIES', 'U') IS NOT NULL
DROP TABLE COUNTRIES;

IF OBJECT_ID('CLIENT', 'U') IS NOT NULL
DROP TABLE CLIENT;

IF OBJECT_ID('CLIENT_OPERATES_IN_COUNTRY', 'U') IS NOT NULL
DROP TABLE CLIENT_OPERATES_IN_COUNTRY;

IF OBJECT_ID('INVENTORY_MOVEMENT', 'U') IS NOT NULL
DROP TABLE INVENTORY_MOVEMENT;

IF OBJECT_ID('CERTIFICATIONS', 'U') IS NOT NULL
DROP TABLE CERTIFICATIONS;
